# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paq < Formula
  desc "Unified CLI for querying installed packages across package managers"
  homepage "https://github.com/cluion/paq"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluion/paq/releases/download/v1.1.0/paq_1.1.0_darwin_amd64.tar.gz"
      sha256 "cdf8c609d658e6b663d64dfb2f99fd28843d36a3023d129daef597665f5896a4"

      define_method(:install) do
        bin.install "paq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluion/paq/releases/download/v1.1.0/paq_1.1.0_darwin_arm64.tar.gz"
      sha256 "3cf1d803996982a7592eab941852623ab73f787be2163b64eba0719cb527bf14"

      define_method(:install) do
        bin.install "paq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluion/paq/releases/download/v1.1.0/paq_1.1.0_linux_amd64.tar.gz"
      sha256 "9c6dbfd743b0561f8e10e8b3a12b813020fa75e89d75f6cbc741a663499314d3"
      define_method(:install) do
        bin.install "paq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluion/paq/releases/download/v1.1.0/paq_1.1.0_linux_arm64.tar.gz"
      sha256 "7b8966b74caba476735844eec260ecf12b65fb4ed0e155aae663966c41ca58a9"
      define_method(:install) do
        bin.install "paq"
      end
    end
  end
end
