# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paq < Formula
  desc "Unified CLI for querying installed packages across package managers"
  homepage "https://github.com/cluion/paq"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluion/paq/releases/download/v1.2.0/paq_1.2.0_darwin_amd64.tar.gz"
      sha256 "1f4647dbb95b4f0518faab14b8bd4f42412212ee3546e7321140bb561a6c58fb"

      define_method(:install) do
        bin.install "paq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluion/paq/releases/download/v1.2.0/paq_1.2.0_darwin_arm64.tar.gz"
      sha256 "b76db6b3dabd6d32d20ff27e746505f98458039acca40c2cd44384af5104c05b"

      define_method(:install) do
        bin.install "paq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluion/paq/releases/download/v1.2.0/paq_1.2.0_linux_amd64.tar.gz"
      sha256 "28be0e5974ee7e12c8f42775728df723f13f0836ba4b96a727959b8029ec3140"
      define_method(:install) do
        bin.install "paq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluion/paq/releases/download/v1.2.0/paq_1.2.0_linux_arm64.tar.gz"
      sha256 "d9394dfc6baae76e9edd7275f8c2c733cbdb78330274028d4f593a0d18ffc1ab"
      define_method(:install) do
        bin.install "paq"
      end
    end
  end
end
