# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZhFinder < Formula
  desc "CLI tool to find Chinese characters (Traditional/Simplified) in files"
  homepage "https://github.com/cluion/zh-finder"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluion/zh-finder/releases/download/v1.0.0/zh-finder_1.0.0_darwin_amd64.tar.gz"
      sha256 "e5df81a78e16eccf73a1abdd1392a36fb7326cb1ecfaad62bab1364d038a9578"

      define_method(:install) do
        bin.install "zh-finder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluion/zh-finder/releases/download/v1.0.0/zh-finder_1.0.0_darwin_arm64.tar.gz"
      sha256 "45b68c7a7a06a18b7d82f6bb980a644a473b01caf299e59a05a6a6b761c339f3"

      define_method(:install) do
        bin.install "zh-finder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluion/zh-finder/releases/download/v1.0.0/zh-finder_1.0.0_linux_amd64.tar.gz"
      sha256 "5ef8a4485ecb197622202a7d6541b4ddf6854482c3def6766eaf99996b6cbc63"
      define_method(:install) do
        bin.install "zh-finder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluion/zh-finder/releases/download/v1.0.0/zh-finder_1.0.0_linux_arm64.tar.gz"
      sha256 "62bfb2d2a1c7fac550b4fcbc34f4263a3f6e2e726908eb7d2850253ae0267244"
      define_method(:install) do
        bin.install "zh-finder"
      end
    end
  end
end
